"""Metropolis-Hastings cryptanalysis for a substitution cipher."""

from __future__ import annotations

import random

import numpy as np

from .bigrams import get_bigrams, transition_matrix
from .cipher import substitute_decrypt, validate_key
from .config import ALPHABET


def random_key(alphabet: str = ALPHABET, seed: int | None = None) -> str:
    """Return a random permutation of ``alphabet``.

    Args:
        alphabet: Alphabet to permute.
        seed: Optional seed for reproducible key generation.

    Returns:
        A string containing each alphabet character exactly once.
    """
    rng = random.Random(seed)
    chars = list(alphabet)
    rng.shuffle(chars)
    return "".join(chars)


def plausibility(text: str, TM_ref: np.ndarray, alphabet: str = ALPHABET) -> float:
    """Compute log-likelihood of ``text`` under a reference bigram matrix.

    ``TM_ref`` must be a relative transition matrix without zero values.
    Observed bigrams are counted as absolute frequencies and evaluated as::

        sum(log(TM_ref[i, j]) * TM_obs[i, j])

    Args:
        text: Candidate plaintext.
        TM_ref: Smoothed relative reference bigram matrix.
        alphabet: Alphabet used for rows and columns.

    Returns:
        Log-likelihood score as a float.

    Raises:
        ValueError: If ``TM_ref`` has a wrong shape or contains non-positive
            values.
    """
    reference = np.asarray(TM_ref, dtype=float)
    expected_shape = (len(alphabet), len(alphabet))

    if reference.shape != expected_shape:
        raise ValueError(f"TM_ref must have shape {expected_shape}.")

    if np.any(reference <= 0.0):
        raise ValueError("TM_ref must not contain zero or negative values.")

    observed = transition_matrix(
        get_bigrams(text),
        alphabet=alphabet,
        smooth_zeros=False,
        normalize=False,
    )

    return float(np.sum(np.log(reference) * observed))


def _swap_two_random_characters(key: str, rng: random.Random) -> str:
    """Return a copy of ``key`` with two random positions swapped."""
    chars = list(key)
    first, second = rng.sample(range(len(chars)), 2)
    chars[first], chars[second] = chars[second], chars[first]
    return "".join(chars)


def prolom_substitute(
    text: str,
    TM_ref: np.ndarray,
    iter: int,
    start_key: str | None = None,
    alphabet: str = ALPHABET,
    seed: int | None = None,
    progress_every: int = 50,
) -> tuple[str, str, float]:
    """Break a substitution cipher with a Metropolis-Hastings search.

    A candidate key is generated by swapping two random characters in the
    current key. Better candidates are accepted automatically. Worse
    candidates are accepted with probability 0.01, matching the assignment
    pseudocode. The function returns the best key and plaintext seen during
    the whole run, not merely the last accepted state.

    Args:
        text: Ciphertext to decrypt.
        TM_ref: Smoothed relative reference bigram matrix.
        iter: Number of Metropolis-Hastings iterations.
        start_key: Optional starting key. If omitted, a random key is used.
        alphabet: Alphabet used by the cipher.
        seed: Optional seed for reproducible random choices.
        progress_every: Print progress every N iterations. Use 0 to disable.

    Returns:
        Tuple ``(best_key, best_decrypted_text, best_score)``.

    Raises:
        ValueError: If ``iter`` is negative, ``start_key`` is invalid, or
            ``TM_ref`` is not a valid reference matrix.
    """
    if iter < 0:
        raise ValueError("iter must be non-negative.")

    rng = random.Random(seed)

    if start_key is None:
        current_chars = list(alphabet)
        rng.shuffle(current_chars)
        current_key = "".join(current_chars)
    else:
        current_key = start_key

    validate_key(current_key, alphabet)

    current_text = substitute_decrypt(text, current_key, alphabet)
    current_score = plausibility(current_text, TM_ref, alphabet)

    best_key = current_key
    best_text = current_text
    best_score = current_score

    for iteration in range(1, iter + 1):
        candidate_key = _swap_two_random_characters(current_key, rng)
        candidate_text = substitute_decrypt(text, candidate_key, alphabet)
        candidate_score = plausibility(candidate_text, TM_ref, alphabet)

        if candidate_score > current_score or rng.random() < 0.01:
            current_key = candidate_key
            current_text = candidate_text
            current_score = candidate_score

        if current_score > best_score:
            best_key = current_key
            best_text = current_text
            best_score = current_score

        if progress_every > 0 and iteration % progress_every == 0:
            print(f"Iteration {iteration} log plausibility: {current_score}")

    return best_key, best_text, best_score
